name: CI/CD Configuration

env:
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
  JWT_S: ${{ secrets.JWT_S }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x' # matches go.mod version

      - name: Install dependencies
        run: go mod tidy

      - name: Test all Go file
        run: go test -v ./...
